##---------------------------------------------------------------------
## StVO-PL options
##---------------------------------------------------------------------
has_points         : true
has_lines          : true
lr_in_parallel     : true
robust_cost        : true
best_lr_matches    : true
use_edlines        : true
scale_points_lines : true
use_lev_marquardt  : false
use_uncertainty    : false
motion_prior       : false

##---------------------------------------------------------------------
## Feature detection parameters
##---------------------------------------------------------------------

# ORB detection parameters
orb_nfeatures    : 1200
orb_scale_factor : 1.2
orb_nlevels      : 1

# LSD detection parameters
lsd_refine       : 2   # 0 NONE - 1 STD - 2 ADV
lsd_scale        : 0.8
lsd_sigma_scale  : 0.6
lsd_quant        : 2.0
lsd_ang_th       : 22.5
lsd_log_eps      : 1.0
lsd_density_th   : 0.6
lsd_n_bins       : 1024

# EDLines detection parameters
edl_ksize        : 15
edl_sigma        : 30.0
edl_gradient_th  : 80
edl_anchor_th    : 8
edl_scan_interv  : 2
edl_min_line_len : 15
edl_fit_err_th   : 1.6

##---------------------------------------------------------------------
## Tracking parameters
##---------------------------------------------------------------------

# Point features
max_dist_epip    : 1.0
min_disp         : 1.0
min_ratio_12_p   : 0.1
max_f2f_disp     : 0.2      # relative to img size

# Line segment features
min_line_length  : 0.015    # relative to img size
min_horiz_angle  : 5.0
max_angle_diff   : 10.0
max_f2f_ang_diff : 10.0
f2f_flow_th      : 100.0
line_horiz_th    : 0.1
desc_th_l        : 0.5

##---------------------------------------------------------------------
## Optimization parameters
##---------------------------------------------------------------------
lambda_lm        : 0.001
lambda_k         : 10.0
homog_th         : 0.0000001
min_features     : 10
max_iters        : 5
max_iters_ref    : 10
min_error        : 0.0000001
min_error_change : 0.0000001
inlier_k         : 2.0
sigma_px         : 1.0
max_optim_error  : 100000.0
